/*** Autogenerated by WIDL 1.1.6 from dcom.idl - Do not edit ***/

#ifndef __REDQ_RPCPROXY_H_VERSION__
#define __REQUIRED_RPCPROXY_H_VERSION__ 440
#endif /* __REDQ_RPCPROXY_H_VERSION__ */

#define __midl_proxy
#include "objbase.h"
#include "rpcproxy.h"
#ifndef __RPCPROXY_H_VERSION__
#error This code needs a newer version of rpcproxy.h
#endif /* __RPCPROXY_H_VERSION__ */

#include "dcom.h"

#include "tgmlog.h"
TGMLOG_DEFAULT_DEBUG_CHANNEL(comps);
#define RpcExceptionInit(filter_func,finally_func) do {} while(0)
#define __DECL_EXCEPTION_FRAME

struct __proxy_frame
{
    __DECL_EXCEPTION_FRAME
    MIDL_STUB_MESSAGE _StubMsg;
    void             *This;
};

static int __proxy_filter( struct __proxy_frame *__frame )
{
    return (__frame->_StubMsg.dwStubPhase != PROXY_SENDRECEIVE);
}

#define TYPE_FORMAT_STRING_SIZE 265
#define PROC_FORMAT_STRING_SIZE 59

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const MIDL_STUB_DESC Object_StubDesc;

/*****************************************************************************
 * IRemUnknown interface
 */
static void __finally_IRemUnknown_RemQueryInterface_Proxy( struct __proxy_frame *__frame )
{
    NdrProxyFreeBuffer( __frame->This, &__frame->_StubMsg );
}

HRESULT STDMETHODCALLTYPE IRemUnknown_RemQueryInterface_Proxy(
    IRemUnknown* This,
    REFIPID ripid,
    ULONG cRefs,
    unsigned short cIids,
    IID *iids,
    REMQIRESULT **ppQIResults)
{
    struct __proxy_frame __f, * const __frame = &__f;
    HRESULT     _RetVal;
    RPC_MESSAGE _RpcMessage;

    RpcExceptionInit( __proxy_filter, __finally_IRemUnknown_RemQueryInterface_Proxy );
    __frame->This = This;
    FB_TRACE("> \n");
    if(ppQIResults)
        MIDL_memset( ppQIResults, 0, sizeof( *ppQIResults ));
    RpcTryExcept
    {
        NdrProxyInitialize(This, &_RpcMessage, &__frame->_StubMsg, &Object_StubDesc, 3);
        if(!ripid)
            RpcRaiseException(RPC_X_NULL_REF_POINTER);
        if(!ppQIResults)
            RpcRaiseException(RPC_X_NULL_REF_POINTER);
        RpcTryFinally
        {
            __frame->_StubMsg.BufferLength = 30;
            NdrPointerBufferSize(
                &__frame->_StubMsg,
                (unsigned char *)ripid,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[20]);



            __frame->_StubMsg.MaxCount = (unsigned long)cIids;

            NdrConformantArrayBufferSize(
                &__frame->_StubMsg,
                (unsigned char *)iids,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[42]);

            NdrProxyGetBuffer(This, &__frame->_StubMsg);
            NdrPointerMarshall(
                &__frame->_StubMsg,
                (unsigned char *)ripid,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[20]);

            MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x4 - (long)__frame->_StubMsg.Buffer) & 0x3);
            __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 3) & ~0x3);
            *(ULONG *)__frame->_StubMsg.Buffer = cRefs;
            __frame->_StubMsg.Buffer += sizeof(ULONG);

            MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x2 - (long)__frame->_StubMsg.Buffer) & 0x1);
            __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 1) & ~0x1);
            *(unsigned short *)__frame->_StubMsg.Buffer = cIids;
            __frame->_StubMsg.Buffer += sizeof(unsigned short);

            __frame->_StubMsg.MaxCount = (unsigned long)cIids;

            NdrConformantArrayMarshall(
                &__frame->_StubMsg,
                (unsigned char *)iids,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[42]);

            NdrProxySendReceive(This, &__frame->_StubMsg);

            __frame->_StubMsg.BufferStart = _RpcMessage.Buffer;
            __frame->_StubMsg.BufferEnd   = __frame->_StubMsg.BufferStart + _RpcMessage.BufferLength;

            if ((_RpcMessage.DataRepresentation & 0xffff) != NDR_LOCAL_DATA_REPRESENTATION)
                NdrConvert( &__frame->_StubMsg, &__MIDL_ProcFormatString.Format[0]);

            NdrPointerUnmarshall(
                &__frame->_StubMsg,
                (unsigned char **)&ppQIResults,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[116],
                0);

            __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 3) & ~0x3);
            if (__frame->_StubMsg.Buffer + sizeof(HRESULT) > __frame->_StubMsg.BufferEnd)
            {
                RpcRaiseException(RPC_X_BAD_STUB_DATA);
            }
            _RetVal = *(HRESULT *)__frame->_StubMsg.Buffer;
            __frame->_StubMsg.Buffer += sizeof(HRESULT);

        }
        RpcFinally
        {
            __finally_IRemUnknown_RemQueryInterface_Proxy( __frame );
        }
        RpcEndFinally
    }
    RpcExcept(__frame->_StubMsg.dwStubPhase != PROXY_SENDRECEIVE)
    {
        __frame->_StubMsg.MaxCount = cIids;

        NdrClearOutParameters( &__frame->_StubMsg, &__MIDL_TypeFormatString.Format[116], (void*)ppQIResults );

        _RetVal = NdrProxyErrorHandler(RpcExceptionCode());
    }
    RpcEndExcept
    FE_TRACE("< \n");
    return _RetVal;
}

struct __frame_IRemUnknown_RemQueryInterface_Stub
{
    __DECL_EXCEPTION_FRAME
    MIDL_STUB_MESSAGE _StubMsg;
    IRemUnknown * _This;
    HRESULT _RetVal;
    REFIPID ripid;
    ULONG cRefs;
    unsigned short cIids;
    IID * iids;
    REMQIRESULT *_W0;
    REMQIRESULT ** ppQIResults;
};

static void __finally_IRemUnknown_RemQueryInterface_Stub( struct __frame_IRemUnknown_RemQueryInterface_Stub *__frame )
{
    NdrPointerFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->ripid,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[20]);



    __frame->_StubMsg.MaxCount = (unsigned long)__frame->cIids;

    NdrConformantArrayFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->iids,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[42]);

    __frame->_StubMsg.MaxCount = (unsigned long)__frame->cIids;

    NdrPointerFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->ppQIResults,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[116]);

}

void __RPC_STUB IRemUnknown_RemQueryInterface_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD* _pdwStubPhase)
{
    struct __frame_IRemUnknown_RemQueryInterface_Stub __f, * const __frame = &__f;

    __frame->_This = (IRemUnknown*)((CStdStubBuffer*)This)->pvServerObject;

    FB_TRACE("< \n");
    NdrStubInitialize(_pRpcMessage, &__frame->_StubMsg, &Object_StubDesc, _pRpcChannelBuffer);

    RpcExceptionInit( 0, __finally_IRemUnknown_RemQueryInterface_Stub );
    __frame->ripid = 0;
    __frame->iids = 0;
    __frame->ppQIResults = 0;

    RpcTryFinally
    {
        if ((_pRpcMessage->DataRepresentation & 0xffff) != NDR_LOCAL_DATA_REPRESENTATION)
            NdrConvert( &__frame->_StubMsg, &__MIDL_ProcFormatString.Format[0]);

        NdrPointerUnmarshall(
            &__frame->_StubMsg,
            (unsigned char **)&__frame->ripid,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[20],
            0);

        __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 3) & ~0x3);
        if (__frame->_StubMsg.Buffer + sizeof(ULONG) > __frame->_StubMsg.BufferEnd)
        {
            RpcRaiseException(RPC_X_BAD_STUB_DATA);
        }
        __frame->cRefs = *(ULONG *)__frame->_StubMsg.Buffer;
        __frame->_StubMsg.Buffer += sizeof(ULONG);

        __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 1) & ~0x1);
        if (__frame->_StubMsg.Buffer + sizeof(unsigned short) > __frame->_StubMsg.BufferEnd)
        {
            RpcRaiseException(RPC_X_BAD_STUB_DATA);
        }
        __frame->cIids = *(unsigned short *)__frame->_StubMsg.Buffer;
        __frame->_StubMsg.Buffer += sizeof(unsigned short);

        NdrConformantArrayUnmarshall(
            &__frame->_StubMsg,
            (unsigned char **)&__frame->iids,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[42],
            0);


        __frame->ppQIResults = &__frame->_W0;
        __frame->_W0 = 0;

        *_pdwStubPhase = STUB_CALL_SERVER;

        __frame->_RetVal = __frame->_This->lpVtbl->RemQueryInterface(__frame->_This, __frame->ripid, __frame->cRefs, __frame->cIids, __frame->iids, __frame->ppQIResults);

        *_pdwStubPhase = STUB_MARSHAL;

        __frame->_StubMsg.BufferLength = 8;
        __frame->_StubMsg.MaxCount = (unsigned long)__frame->cIids;

        NdrPointerBufferSize(
            &__frame->_StubMsg,
            (unsigned char *)__frame->ppQIResults,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[116]);


        NdrStubGetBuffer(This, _pRpcChannelBuffer, &__frame->_StubMsg);
        __frame->_StubMsg.MaxCount = (unsigned long)__frame->cIids;

        NdrPointerMarshall(
            &__frame->_StubMsg,
            (unsigned char *)__frame->ppQIResults,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[116]);


        MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x4 - (long)__frame->_StubMsg.Buffer) & 0x3);
        __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 3) & ~0x3);
        *(HRESULT *)__frame->_StubMsg.Buffer = __frame->_RetVal;
        __frame->_StubMsg.Buffer += sizeof(HRESULT);

    }
    RpcFinally
    {
        __finally_IRemUnknown_RemQueryInterface_Stub( __frame );
    }
    RpcEndFinally
    _pRpcMessage->BufferLength = __frame->_StubMsg.Buffer - (unsigned char *)_pRpcMessage->Buffer;
    FE_TRACE("> \n");
}

static void __finally_IRemUnknown_RemAddRef_Proxy( struct __proxy_frame *__frame )
{
    NdrProxyFreeBuffer( __frame->This, &__frame->_StubMsg );
}

HRESULT STDMETHODCALLTYPE IRemUnknown_RemAddRef_Proxy(
    IRemUnknown* This,
    unsigned short cInterfaceRefs,
    REMINTERFACEREF *InterfaceRefs,
    HRESULT *pResults)
{
    struct __proxy_frame __f, * const __frame = &__f;
    HRESULT     _RetVal;
    RPC_MESSAGE _RpcMessage;

    RpcExceptionInit( __proxy_filter, __finally_IRemUnknown_RemAddRef_Proxy );
    __frame->This = This;
    FB_TRACE("> \n");
    if(pResults)
        MIDL_memset( pResults, 0, sizeof( *pResults ));
    RpcTryExcept
    {
        NdrProxyInitialize(This, &_RpcMessage, &__frame->_StubMsg, &Object_StubDesc, 4);
        RpcTryFinally
        {
            __frame->_StubMsg.BufferLength = 6;

            __frame->_StubMsg.MaxCount = (unsigned long)cInterfaceRefs;

            NdrConformantArrayBufferSize(
                &__frame->_StubMsg,
                (unsigned char *)InterfaceRefs,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[132]);

            NdrProxyGetBuffer(This, &__frame->_StubMsg);
            MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x2 - (long)__frame->_StubMsg.Buffer) & 0x1);
            __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 1) & ~0x1);
            *(unsigned short *)__frame->_StubMsg.Buffer = cInterfaceRefs;
            __frame->_StubMsg.Buffer += sizeof(unsigned short);

            __frame->_StubMsg.MaxCount = (unsigned long)cInterfaceRefs;

            NdrConformantArrayMarshall(
                &__frame->_StubMsg,
                (unsigned char *)InterfaceRefs,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[132]);

            NdrProxySendReceive(This, &__frame->_StubMsg);

            __frame->_StubMsg.BufferStart = _RpcMessage.Buffer;
            __frame->_StubMsg.BufferEnd   = __frame->_StubMsg.BufferStart + _RpcMessage.BufferLength;

            if ((_RpcMessage.DataRepresentation & 0xffff) != NDR_LOCAL_DATA_REPRESENTATION)
                NdrConvert( &__frame->_StubMsg, &__MIDL_ProcFormatString.Format[18]);

            NdrConformantArrayUnmarshall(
                &__frame->_StubMsg,
                (unsigned char **)&pResults,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[146],
                0);

            __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 3) & ~0x3);
            if (__frame->_StubMsg.Buffer + sizeof(HRESULT) > __frame->_StubMsg.BufferEnd)
            {
                RpcRaiseException(RPC_X_BAD_STUB_DATA);
            }
            _RetVal = *(HRESULT *)__frame->_StubMsg.Buffer;
            __frame->_StubMsg.Buffer += sizeof(HRESULT);

        }
        RpcFinally
        {
            __finally_IRemUnknown_RemAddRef_Proxy( __frame );
        }
        RpcEndFinally
    }
    RpcExcept(__frame->_StubMsg.dwStubPhase != PROXY_SENDRECEIVE)
    {
        __frame->_StubMsg.MaxCount = cInterfaceRefs;

        NdrClearOutParameters( &__frame->_StubMsg, &__MIDL_TypeFormatString.Format[146], (void*)pResults );

        _RetVal = NdrProxyErrorHandler(RpcExceptionCode());
    }
    RpcEndExcept
    FE_TRACE("< \n");
    return _RetVal;
}

struct __frame_IRemUnknown_RemAddRef_Stub
{
    __DECL_EXCEPTION_FRAME
    MIDL_STUB_MESSAGE _StubMsg;
    IRemUnknown * _This;
    HRESULT _RetVal;
    unsigned short cInterfaceRefs;
    REMINTERFACEREF * InterfaceRefs;
    HRESULT * pResults;
};

static void __finally_IRemUnknown_RemAddRef_Stub( struct __frame_IRemUnknown_RemAddRef_Stub *__frame )
{

    __frame->_StubMsg.MaxCount = (unsigned long)__frame->cInterfaceRefs;

    NdrConformantArrayFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->InterfaceRefs,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[132]);

    __frame->_StubMsg.MaxCount = (unsigned long)__frame->cInterfaceRefs;

    NdrConformantArrayFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->pResults,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[146]);
    if (__frame->pResults)
        __frame->_StubMsg.pfnFree(__frame->pResults);

}

void __RPC_STUB IRemUnknown_RemAddRef_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD* _pdwStubPhase)
{
    struct __frame_IRemUnknown_RemAddRef_Stub __f, * const __frame = &__f;

    __frame->_This = (IRemUnknown*)((CStdStubBuffer*)This)->pvServerObject;

    FB_TRACE("< \n");
    NdrStubInitialize(_pRpcMessage, &__frame->_StubMsg, &Object_StubDesc, _pRpcChannelBuffer);

    RpcExceptionInit( 0, __finally_IRemUnknown_RemAddRef_Stub );
    __frame->InterfaceRefs = 0;
    __frame->pResults = 0;

    RpcTryFinally
    {
        if ((_pRpcMessage->DataRepresentation & 0xffff) != NDR_LOCAL_DATA_REPRESENTATION)
            NdrConvert( &__frame->_StubMsg, &__MIDL_ProcFormatString.Format[18]);

        __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 1) & ~0x1);
        if (__frame->_StubMsg.Buffer + sizeof(unsigned short) > __frame->_StubMsg.BufferEnd)
        {
            RpcRaiseException(RPC_X_BAD_STUB_DATA);
        }
        __frame->cInterfaceRefs = *(unsigned short *)__frame->_StubMsg.Buffer;
        __frame->_StubMsg.Buffer += sizeof(unsigned short);

        NdrConformantArrayUnmarshall(
            &__frame->_StubMsg,
            (unsigned char **)&__frame->InterfaceRefs,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[132],
            0);


        __frame->pResults = NdrAllocate(&__frame->_StubMsg, __frame->cInterfaceRefs * 4);

        *_pdwStubPhase = STUB_CALL_SERVER;

        __frame->_RetVal = __frame->_This->lpVtbl->RemAddRef(__frame->_This, __frame->cInterfaceRefs, __frame->InterfaceRefs, __frame->pResults);

        *_pdwStubPhase = STUB_MARSHAL;

        __frame->_StubMsg.BufferLength = 8;
        __frame->_StubMsg.MaxCount = (unsigned long)__frame->cInterfaceRefs;

        NdrConformantArrayBufferSize(
            &__frame->_StubMsg,
            (unsigned char *)__frame->pResults,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[146]);


        NdrStubGetBuffer(This, _pRpcChannelBuffer, &__frame->_StubMsg);
        __frame->_StubMsg.MaxCount = (unsigned long)__frame->cInterfaceRefs;

        NdrConformantArrayMarshall(
            &__frame->_StubMsg,
            (unsigned char *)__frame->pResults,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[146]);


        MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x4 - (long)__frame->_StubMsg.Buffer) & 0x3);
        __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 3) & ~0x3);
        *(HRESULT *)__frame->_StubMsg.Buffer = __frame->_RetVal;
        __frame->_StubMsg.Buffer += sizeof(HRESULT);

    }
    RpcFinally
    {
        __finally_IRemUnknown_RemAddRef_Stub( __frame );
    }
    RpcEndFinally
    _pRpcMessage->BufferLength = __frame->_StubMsg.Buffer - (unsigned char *)_pRpcMessage->Buffer;
    FE_TRACE("> \n");
}

static void __finally_IRemUnknown_RemRelease_Proxy( struct __proxy_frame *__frame )
{
    NdrProxyFreeBuffer( __frame->This, &__frame->_StubMsg );
}

HRESULT STDMETHODCALLTYPE IRemUnknown_RemRelease_Proxy(
    IRemUnknown* This,
    unsigned short cInterfaceRefs,
    REMINTERFACEREF *InterfaceRefs)
{
    struct __proxy_frame __f, * const __frame = &__f;
    HRESULT     _RetVal;
    RPC_MESSAGE _RpcMessage;

    RpcExceptionInit( __proxy_filter, __finally_IRemUnknown_RemRelease_Proxy );
    __frame->This = This;
    FB_TRACE("> \n");
    RpcTryExcept
    {
        NdrProxyInitialize(This, &_RpcMessage, &__frame->_StubMsg, &Object_StubDesc, 5);
        RpcTryFinally
        {
            __frame->_StubMsg.BufferLength = 6;

            __frame->_StubMsg.MaxCount = (unsigned long)cInterfaceRefs;

            NdrConformantArrayBufferSize(
                &__frame->_StubMsg,
                (unsigned char *)InterfaceRefs,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[156]);

            NdrProxyGetBuffer(This, &__frame->_StubMsg);
            MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x2 - (long)__frame->_StubMsg.Buffer) & 0x1);
            __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 1) & ~0x1);
            *(unsigned short *)__frame->_StubMsg.Buffer = cInterfaceRefs;
            __frame->_StubMsg.Buffer += sizeof(unsigned short);

            __frame->_StubMsg.MaxCount = (unsigned long)cInterfaceRefs;

            NdrConformantArrayMarshall(
                &__frame->_StubMsg,
                (unsigned char *)InterfaceRefs,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[156]);

            NdrProxySendReceive(This, &__frame->_StubMsg);

            __frame->_StubMsg.BufferStart = _RpcMessage.Buffer;
            __frame->_StubMsg.BufferEnd   = __frame->_StubMsg.BufferStart + _RpcMessage.BufferLength;

            if ((_RpcMessage.DataRepresentation & 0xffff) != NDR_LOCAL_DATA_REPRESENTATION)
                NdrConvert( &__frame->_StubMsg, &__MIDL_ProcFormatString.Format[30]);

            __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 3) & ~0x3);
            if (__frame->_StubMsg.Buffer + sizeof(HRESULT) > __frame->_StubMsg.BufferEnd)
            {
                RpcRaiseException(RPC_X_BAD_STUB_DATA);
            }
            _RetVal = *(HRESULT *)__frame->_StubMsg.Buffer;
            __frame->_StubMsg.Buffer += sizeof(HRESULT);

        }
        RpcFinally
        {
            __finally_IRemUnknown_RemRelease_Proxy( __frame );
        }
        RpcEndFinally
    }
    RpcExcept(__frame->_StubMsg.dwStubPhase != PROXY_SENDRECEIVE)
    {
        _RetVal = NdrProxyErrorHandler(RpcExceptionCode());
    }
    RpcEndExcept
    FE_TRACE("< \n");
    return _RetVal;
}

struct __frame_IRemUnknown_RemRelease_Stub
{
    __DECL_EXCEPTION_FRAME
    MIDL_STUB_MESSAGE _StubMsg;
    IRemUnknown * _This;
    HRESULT _RetVal;
    unsigned short cInterfaceRefs;
    REMINTERFACEREF * InterfaceRefs;
};

static void __finally_IRemUnknown_RemRelease_Stub( struct __frame_IRemUnknown_RemRelease_Stub *__frame )
{

    __frame->_StubMsg.MaxCount = (unsigned long)__frame->cInterfaceRefs;

    NdrConformantArrayFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->InterfaceRefs,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[156]);

}

void __RPC_STUB IRemUnknown_RemRelease_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD* _pdwStubPhase)
{
    struct __frame_IRemUnknown_RemRelease_Stub __f, * const __frame = &__f;

    __frame->_This = (IRemUnknown*)((CStdStubBuffer*)This)->pvServerObject;

    FB_TRACE("< \n");
    NdrStubInitialize(_pRpcMessage, &__frame->_StubMsg, &Object_StubDesc, _pRpcChannelBuffer);

    RpcExceptionInit( 0, __finally_IRemUnknown_RemRelease_Stub );
    __frame->InterfaceRefs = 0;

    RpcTryFinally
    {
        if ((_pRpcMessage->DataRepresentation & 0xffff) != NDR_LOCAL_DATA_REPRESENTATION)
            NdrConvert( &__frame->_StubMsg, &__MIDL_ProcFormatString.Format[30]);

        __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 1) & ~0x1);
        if (__frame->_StubMsg.Buffer + sizeof(unsigned short) > __frame->_StubMsg.BufferEnd)
        {
            RpcRaiseException(RPC_X_BAD_STUB_DATA);
        }
        __frame->cInterfaceRefs = *(unsigned short *)__frame->_StubMsg.Buffer;
        __frame->_StubMsg.Buffer += sizeof(unsigned short);

        NdrConformantArrayUnmarshall(
            &__frame->_StubMsg,
            (unsigned char **)&__frame->InterfaceRefs,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[156],
            0);


        *_pdwStubPhase = STUB_CALL_SERVER;

        __frame->_RetVal = __frame->_This->lpVtbl->RemRelease(__frame->_This, __frame->cInterfaceRefs, __frame->InterfaceRefs);

        *_pdwStubPhase = STUB_MARSHAL;

        __frame->_StubMsg.BufferLength = 8;

        NdrStubGetBuffer(This, _pRpcChannelBuffer, &__frame->_StubMsg);

        MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x4 - (long)__frame->_StubMsg.Buffer) & 0x3);
        __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 3) & ~0x3);
        *(HRESULT *)__frame->_StubMsg.Buffer = __frame->_RetVal;
        __frame->_StubMsg.Buffer += sizeof(HRESULT);

    }
    RpcFinally
    {
        __finally_IRemUnknown_RemRelease_Stub( __frame );
    }
    RpcEndFinally
    _pRpcMessage->BufferLength = __frame->_StubMsg.Buffer - (unsigned char *)_pRpcMessage->Buffer;
    FE_TRACE("> \n");
}

static const CINTERFACE_PROXY_VTABLE(6) _IRemUnknownProxyVtbl =
{
    {
        &IID_IRemUnknown,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        IRemUnknown_RemQueryInterface_Proxy,
        IRemUnknown_RemAddRef_Proxy,
        IRemUnknown_RemRelease_Proxy
    }
};


static const PRPC_STUB_FUNCTION IRemUnknown_table[] =
{
    IRemUnknown_RemQueryInterface_Stub,
    IRemUnknown_RemAddRef_Stub,
    IRemUnknown_RemRelease_Stub
};

static const CInterfaceStubVtbl _IRemUnknownStubVtbl =
{
    {
        &IID_IRemUnknown,
        0,
        6,
        &IRemUnknown_table[-3],
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IRemUnknown2 interface
 */
static void __finally_IRemUnknown2_RemQueryInterface2_Proxy( struct __proxy_frame *__frame )
{
    NdrProxyFreeBuffer( __frame->This, &__frame->_StubMsg );
}

HRESULT STDMETHODCALLTYPE IRemUnknown2_RemQueryInterface2_Proxy(
    IRemUnknown2* This,
    REFIPID ripid,
    unsigned short cIids,
    IID *iids,
    HRESULT *phr,
    MInterfacePointer **ppMIF)
{
    struct __proxy_frame __f, * const __frame = &__f;
    HRESULT     _RetVal;
    RPC_MESSAGE _RpcMessage;

    RpcExceptionInit( __proxy_filter, __finally_IRemUnknown2_RemQueryInterface2_Proxy );
    __frame->This = This;
    FB_TRACE("> \n");
    if(phr)
        MIDL_memset( phr, 0, sizeof( *phr ));
    if(ppMIF)
        MIDL_memset( ppMIF, 0, sizeof( *ppMIF ));
    RpcTryExcept
    {
        NdrProxyInitialize(This, &_RpcMessage, &__frame->_StubMsg, &Object_StubDesc, 6);
        if(!ripid)
            RpcRaiseException(RPC_X_NULL_REF_POINTER);
        RpcTryFinally
        {
            __frame->_StubMsg.BufferLength = 22;
            NdrPointerBufferSize(
                &__frame->_StubMsg,
                (unsigned char *)ripid,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[188]);


            __frame->_StubMsg.MaxCount = (unsigned long)cIids;

            NdrConformantArrayBufferSize(
                &__frame->_StubMsg,
                (unsigned char *)iids,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[192]);

            NdrProxyGetBuffer(This, &__frame->_StubMsg);
            NdrPointerMarshall(
                &__frame->_StubMsg,
                (unsigned char *)ripid,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[188]);

            MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x2 - (long)__frame->_StubMsg.Buffer) & 0x1);
            __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 1) & ~0x1);
            *(unsigned short *)__frame->_StubMsg.Buffer = cIids;
            __frame->_StubMsg.Buffer += sizeof(unsigned short);

            __frame->_StubMsg.MaxCount = (unsigned long)cIids;

            NdrConformantArrayMarshall(
                &__frame->_StubMsg,
                (unsigned char *)iids,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[192]);

            NdrProxySendReceive(This, &__frame->_StubMsg);

            __frame->_StubMsg.BufferStart = _RpcMessage.Buffer;
            __frame->_StubMsg.BufferEnd   = __frame->_StubMsg.BufferStart + _RpcMessage.BufferLength;

            if ((_RpcMessage.DataRepresentation & 0xffff) != NDR_LOCAL_DATA_REPRESENTATION)
                NdrConvert( &__frame->_StubMsg, &__MIDL_ProcFormatString.Format[38]);

            NdrConformantArrayUnmarshall(
                &__frame->_StubMsg,
                (unsigned char **)&phr,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[206],
                0);

            NdrConformantArrayUnmarshall(
                &__frame->_StubMsg,
                (unsigned char **)&ppMIF,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[234],
                0);

            __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 3) & ~0x3);
            if (__frame->_StubMsg.Buffer + sizeof(HRESULT) > __frame->_StubMsg.BufferEnd)
            {
                RpcRaiseException(RPC_X_BAD_STUB_DATA);
            }
            _RetVal = *(HRESULT *)__frame->_StubMsg.Buffer;
            __frame->_StubMsg.Buffer += sizeof(HRESULT);

        }
        RpcFinally
        {
            __finally_IRemUnknown2_RemQueryInterface2_Proxy( __frame );
        }
        RpcEndFinally
    }
    RpcExcept(__frame->_StubMsg.dwStubPhase != PROXY_SENDRECEIVE)
    {
        __frame->_StubMsg.MaxCount = cIids;

        NdrClearOutParameters( &__frame->_StubMsg, &__MIDL_TypeFormatString.Format[206], (void*)phr );

        __frame->_StubMsg.MaxCount = cIids;

        NdrClearOutParameters( &__frame->_StubMsg, &__MIDL_TypeFormatString.Format[234], (void*)ppMIF );

        _RetVal = NdrProxyErrorHandler(RpcExceptionCode());
    }
    RpcEndExcept
    FE_TRACE("< \n");
    return _RetVal;
}

struct __frame_IRemUnknown2_RemQueryInterface2_Stub
{
    __DECL_EXCEPTION_FRAME
    MIDL_STUB_MESSAGE _StubMsg;
    IRemUnknown2 * _This;
    HRESULT _RetVal;
    REFIPID ripid;
    unsigned short cIids;
    IID * iids;
    HRESULT * phr;
    MInterfacePointer ** ppMIF;
};

static void __finally_IRemUnknown2_RemQueryInterface2_Stub( struct __frame_IRemUnknown2_RemQueryInterface2_Stub *__frame )
{
    NdrPointerFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->ripid,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[188]);


    __frame->_StubMsg.MaxCount = (unsigned long)__frame->cIids;

    NdrConformantArrayFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->iids,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[192]);

    __frame->_StubMsg.MaxCount = (unsigned long)__frame->cIids;

    NdrConformantArrayFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->phr,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[206]);
    if (__frame->phr)
        __frame->_StubMsg.pfnFree(__frame->phr);

    __frame->_StubMsg.MaxCount = (unsigned long)__frame->cIids;

    NdrConformantArrayFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->ppMIF,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[234]);
    if (__frame->ppMIF)
        __frame->_StubMsg.pfnFree(__frame->ppMIF);

}

void __RPC_STUB IRemUnknown2_RemQueryInterface2_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD* _pdwStubPhase)
{
    struct __frame_IRemUnknown2_RemQueryInterface2_Stub __f, * const __frame = &__f;

    __frame->_This = (IRemUnknown2*)((CStdStubBuffer*)This)->pvServerObject;

    FB_TRACE("< \n");
    NdrStubInitialize(_pRpcMessage, &__frame->_StubMsg, &Object_StubDesc, _pRpcChannelBuffer);

    RpcExceptionInit( 0, __finally_IRemUnknown2_RemQueryInterface2_Stub );
    __frame->ripid = 0;
    __frame->iids = 0;
    __frame->phr = 0;
    __frame->ppMIF = 0;

    RpcTryFinally
    {
        if ((_pRpcMessage->DataRepresentation & 0xffff) != NDR_LOCAL_DATA_REPRESENTATION)
            NdrConvert( &__frame->_StubMsg, &__MIDL_ProcFormatString.Format[38]);

        NdrPointerUnmarshall(
            &__frame->_StubMsg,
            (unsigned char **)&__frame->ripid,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[188],
            0);

        __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 1) & ~0x1);
        if (__frame->_StubMsg.Buffer + sizeof(unsigned short) > __frame->_StubMsg.BufferEnd)
        {
            RpcRaiseException(RPC_X_BAD_STUB_DATA);
        }
        __frame->cIids = *(unsigned short *)__frame->_StubMsg.Buffer;
        __frame->_StubMsg.Buffer += sizeof(unsigned short);

        NdrConformantArrayUnmarshall(
            &__frame->_StubMsg,
            (unsigned char **)&__frame->iids,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[192],
            0);


        __frame->phr = NdrAllocate(&__frame->_StubMsg, __frame->cIids * 4);
        __frame->ppMIF = NdrAllocate(&__frame->_StubMsg, __frame->cIids * 4);

        *_pdwStubPhase = STUB_CALL_SERVER;

        __frame->_RetVal = __frame->_This->lpVtbl->RemQueryInterface2(__frame->_This, __frame->ripid, __frame->cIids, __frame->iids, __frame->phr, __frame->ppMIF);

        *_pdwStubPhase = STUB_MARSHAL;

        __frame->_StubMsg.BufferLength = 8;
        __frame->_StubMsg.MaxCount = (unsigned long)__frame->cIids;

        NdrConformantArrayBufferSize(
            &__frame->_StubMsg,
            (unsigned char *)__frame->phr,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[206]);

        __frame->_StubMsg.MaxCount = (unsigned long)__frame->cIids;

        NdrConformantArrayBufferSize(
            &__frame->_StubMsg,
            (unsigned char *)__frame->ppMIF,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[234]);


        NdrStubGetBuffer(This, _pRpcChannelBuffer, &__frame->_StubMsg);
        __frame->_StubMsg.MaxCount = (unsigned long)__frame->cIids;

        NdrConformantArrayMarshall(
            &__frame->_StubMsg,
            (unsigned char *)__frame->phr,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[206]);

        __frame->_StubMsg.MaxCount = (unsigned long)__frame->cIids;

        NdrConformantArrayMarshall(
            &__frame->_StubMsg,
            (unsigned char *)__frame->ppMIF,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[234]);


        MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x4 - (long)__frame->_StubMsg.Buffer) & 0x3);
        __frame->_StubMsg.Buffer = (unsigned char *)(((long)__frame->_StubMsg.Buffer + 3) & ~0x3);
        *(HRESULT *)__frame->_StubMsg.Buffer = __frame->_RetVal;
        __frame->_StubMsg.Buffer += sizeof(HRESULT);

    }
    RpcFinally
    {
        __finally_IRemUnknown2_RemQueryInterface2_Stub( __frame );
    }
    RpcEndFinally
    _pRpcMessage->BufferLength = __frame->_StubMsg.Buffer - (unsigned char *)_pRpcMessage->Buffer;
    FE_TRACE("> \n");
}

static const CINTERFACE_PROXY_VTABLE(7) _IRemUnknown2ProxyVtbl =
{
    {
        &IID_IRemUnknown2,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        0  /* IRemUnknown_RemQueryInterface_Proxy */,
        0  /* IRemUnknown_RemAddRef_Proxy */,
        0  /* IRemUnknown_RemRelease_Proxy */,
        IRemUnknown2_RemQueryInterface2_Proxy
    }
};


static const PRPC_STUB_FUNCTION IRemUnknown2_table[] =
{
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION,
    IRemUnknown2_RemQueryInterface2_Stub
};

static const CInterfaceStubVtbl _IRemUnknown2StubVtbl =
{
    {
        &IID_IRemUnknown2,
        0,
        7,
        &IRemUnknown2_table[-3],
    },
    {
        CStdStubBuffer_METHODS
    }
};

static const MIDL_STUB_DESC Object_StubDesc =
{
    0,
    NdrOleAllocate,
    NdrOleFree,
    {0}, 0, 0, 0, 0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x10001, /* Ndr library version */
    0,
    0x50100a4, /* MIDL Version 5.1.164 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

#if !defined(__RPC_WIN32__)
#error Currently only Wine and WIN32 are supported.
#endif

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
        0x4d,    /* FC_IN_PARAM */
        0x01,
        NdrFcShort(0x14),
        0x4e,    /* FC_IN_PARAM_BASETYPE */
        0x09,    /* FC_ULONG */
        0x4e,    /* FC_IN_PARAM_BASETYPE */
        0x07,    /* FC_USHORT */
        0x4d,    /* FC_IN_PARAM */
        0x01,
        NdrFcShort(0x2a),
        0x51,    /* FC_OUT_PARAM */
        0x01,
        NdrFcShort(0x74),
        0x53,    /* FC_RETURN_PARAM_BASETYPE */
        0x08,    /* FC_LONG */
        0x4e,    /* FC_IN_PARAM_BASETYPE */
        0x07,    /* FC_USHORT */
        0x4d,    /* FC_IN_PARAM */
        0x01,
        NdrFcShort(0x84),
        0x51,    /* FC_OUT_PARAM */
        0x01,
        NdrFcShort(0x92),
        0x53,    /* FC_RETURN_PARAM_BASETYPE */
        0x08,    /* FC_LONG */
        0x4e,    /* FC_IN_PARAM_BASETYPE */
        0x07,    /* FC_USHORT */
        0x4d,    /* FC_IN_PARAM */
        0x01,
        NdrFcShort(0x9c),
        0x53,    /* FC_RETURN_PARAM_BASETYPE */
        0x08,    /* FC_LONG */
        0x4d,    /* FC_IN_PARAM */
        0x01,
        NdrFcShort(0xbc),
        0x4e,    /* FC_IN_PARAM_BASETYPE */
        0x07,    /* FC_USHORT */
        0x4d,    /* FC_IN_PARAM */
        0x01,
        NdrFcShort(0xc0),
        0x51,    /* FC_OUT_PARAM */
        0x01,
        NdrFcShort(0xce),
        0x51,    /* FC_OUT_PARAM */
        0x01,
        NdrFcShort(0xea),
        0x53,    /* FC_RETURN_PARAM_BASETYPE */
        0x08,    /* FC_LONG */
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (unsigned char[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x02,	/* FC_CHAR */
        0x5b,		/* FC_END */
/* 8 (GUID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x09,	/* FC_ULONG */
        0x07,	/* FC_USHORT */
        0x07,	/* FC_USHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xfff1),	/* Offset= -15 (2) */
        0x5b,		/* FC_END */
/* 20 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfffffff2),	/* 8 */
/* 24 (unsigned char[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x02,	/* FC_CHAR */
        0x5b,		/* FC_END */
/* 30 (IID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x09,	/* FC_ULONG */
        0x07,	/* FC_USHORT */
        0x07,	/* FC_USHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xfff1),	/* Offset= -15 (24) */
        0x5b,		/* FC_END */
/* 42 (IID *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x20,	/* Corr desc: parameter */
        0x0,
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xffea),	/* Offset= -22 (30) */
        0x5c,		/* FC_PAD */
        0x5b,		/* FC_END */
/* 56 (unsigned char[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x02,	/* FC_CHAR */
        0x5b,		/* FC_END */
/* 62 (IPID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x09,	/* FC_ULONG */
        0x07,	/* FC_USHORT */
        0x07,	/* FC_USHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xfff1),	/* Offset= -15 (56) */
        0x5b,		/* FC_END */
/* 74 (STDOBJREF) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x28),	/* 40 */
        0x09,	/* FC_ULONG */
        0x09,	/* FC_ULONG */
        0x0b,	/* FC_HYPER */
        0x0b,	/* FC_HYPER */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xffea),	/* Offset= -22 (62) */
        0x5c,		/* FC_PAD */
        0x5b,		/* FC_END */
/* 88 (REMQIRESULT) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x2c),	/* 44 */
        0x08,	/* FC_LONG */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xffeb),	/* Offset= -21 (74) */
        0x5b,		/* FC_END */
/* 98 (REMQIRESULT *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x2c),	/* 44 */
        0x20,	/* Corr desc: parameter */
        0x0,
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xffec),	/* Offset= -20 (88) */
        0x5c,		/* FC_PAD */
        0x5b,		/* FC_END */
/* 112 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xfff0),	/* Offset= -16 (98) */
/* 116 */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffffffa),	/* 112 */
/* 120 (REMINTERFACEREF) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xffc0),	/* Offset= -64 (62) */
        0x09,	/* FC_ULONG */
        0x09,	/* FC_ULONG */
        0x5c,		/* FC_PAD */
        0x5b,		/* FC_END */
/* 132 (REMINTERFACEREF *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        0x20,	/* Corr desc: parameter */
        0x0,
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xffea),	/* Offset= -22 (120) */
        0x5c,		/* FC_PAD */
        0x5b,		/* FC_END */
/* 146 (HRESULT *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x20,	/* Corr desc: parameter */
        0x0,
        NdrFcShort(0x0),
        0x08,	/* FC_LONG */
        0x5b,		/* FC_END */
/* 156 (REMINTERFACEREF *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        0x20,	/* Corr desc: parameter */
        0x0,
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xffd2),	/* Offset= -46 (120) */
        0x5c,		/* FC_PAD */
        0x5b,		/* FC_END */
/* 170 (unsigned char[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x02,	/* FC_CHAR */
        0x5b,		/* FC_END */
/* 176 (GUID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x09,	/* FC_ULONG */
        0x07,	/* FC_USHORT */
        0x07,	/* FC_USHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xfff1),	/* Offset= -15 (170) */
        0x5b,		/* FC_END */
/* 188 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfffffff2),	/* 176 */
/* 192 (IID *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x20,	/* Corr desc: parameter */
        0x0,
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,	/* FIXME: padding */
        NdrFcShort(0xff54),	/* Offset= -172 (30) */
        0x5c,		/* FC_PAD */
        0x5b,		/* FC_END */
/* 206 (HRESULT *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x20,	/* Corr desc: parameter */
        0x0,
        NdrFcShort(0x0),
        0x08,	/* FC_LONG */
        0x5b,		/* FC_END */
/* 216 (BYTE[]) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x9, /* Corr desc: FC_ULONG */
        0x0, /* no operators */
        NdrFcShort(0xfffffffc), /* offset = -4 */
        0x02,	/* FC_CHAR */
        0x5b,		/* FC_END */
/* 226 (MInterfacePointer) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        NdrFcShort(0xfff2),	/* Offset= -14 (216) */
        0x09,	/* FC_ULONG */
        0x5b,		/* FC_END */
/* 234 (MInterfacePointer **) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x20,	/* Corr desc: parameter */
        0x0,
        NdrFcShort(0x0),
        0x4b, /* FC_PP */
        0x5c, /* FC_PAD */
        0x48, /* FC_VARIABLE_REPEAT */
        0x49, /* FC_FIXED_OFFSET */
        NdrFcShort(0x4), /* Increment = 4 */
        NdrFcShort(0x0), /* Offset to array = 0 */
        NdrFcShort(0x1), /* Number of pointers = 1 */
        NdrFcShort(0x0), /* Memory offset = 0 */
        NdrFcShort(0x0), /* Buffer offset = 0 */
/* 256 (MInterfacePointer *) */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffe0),	/* Offset= -32 (226) */
        0x5b, /* FC_END */
        0x8,	/* FC_LONG */
        0x5c,		/* FC_PAD */
        0x5b,		/* FC_END */
        0x0
    }
};

static const CInterfaceProxyVtbl* const _dcom_ProxyVtblList[] =
{
    (const CInterfaceProxyVtbl*)&_IRemUnknownProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IRemUnknown2ProxyVtbl,
    0
};

static const CInterfaceStubVtbl* const _dcom_StubVtblList[] =
{
    (const CInterfaceStubVtbl*)&_IRemUnknownStubVtbl,
    (const CInterfaceStubVtbl*)&_IRemUnknown2StubVtbl,
    0
};

static PCInterfaceName const _dcom_InterfaceNamesList[] =
{
    "IRemUnknown",
    "IRemUnknown2",
    0
};

#define _dcom_CHECK_IID(n) IID_GENERIC_CHECK_IID(_dcom, pIID, n)

int __stdcall _dcom_IID_Lookup(const IID* pIID, int* pIndex)
{
    if (!_dcom_CHECK_IID(0))
    {
        *pIndex = 0;
        return 1;
    }
    if (!_dcom_CHECK_IID(1))
    {
        *pIndex = 1;
        return 1;
    }
    return 0;
}

const ExtendedProxyFileInfo dcom_ProxyFileInfo =
{
    (const PCInterfaceProxyVtblList*)&_dcom_ProxyVtblList,
    (const PCInterfaceStubVtblList*)&_dcom_StubVtblList,
    _dcom_InterfaceNamesList,
    0,
    &_dcom_IID_Lookup,
    2,
    1,
    0,
    0,
    0,
    0
};
