/*** Autogenerated by WIDL 1.1.6 from scm_api.idl - Do not edit ***/
#include <rpc.h>
#include <rpcndr.h>

#ifndef __WIDL_SCM_API_H
#define __WIDL_SCM_API_H
#ifdef __cplusplus
extern "C" {
#endif

#include <unknwn.h>
#include "dcom.h"
#ifndef __ISCMClsFactoryResloveService_FWD_DEFINED__
#define __ISCMClsFactoryResloveService_FWD_DEFINED__
typedef interface ISCMClsFactoryResloveService ISCMClsFactoryResloveService;
#endif

/*****************************************************************************
 * ISCMClsFactoryResloveService interface
 */
#ifndef __ISCMClsFactoryResloveService_INTERFACE_DEFINED__
#define __ISCMClsFactoryResloveService_INTERFACE_DEFINED__

DEFINE_GUID(IID_ISCMClsFactoryResloveService, 0x03ee1f1b, 0x7f8b, 0x4fdb, 0x86,0x0a, 0x02,0x95,0x85,0x6c,0xdb,0x21);
#if defined(__cplusplus) && !defined(CINTERFACE)
interface ISCMClsFactoryResloveService : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Register(
        REFIID in_clsid,
        int in_size,
        const unsigned char *in_data) = 0;

    virtual HRESULT STDMETHODCALLTYPE Unregister(
        REFIID in_clsid) = 0;

    virtual HRESULT STDMETHODCALLTYPE Query(
        REFIID in_clsid,
        int in_size,
        unsigned char *out_data,
        int *out_length) = 0;

};
#else
typedef struct ISCMClsFactoryResloveServiceVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ISCMClsFactoryResloveService* This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ISCMClsFactoryResloveService* This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ISCMClsFactoryResloveService* This);

    /*** ISCMClsFactoryResloveService methods ***/
    HRESULT (STDMETHODCALLTYPE *Register)(
        ISCMClsFactoryResloveService* This,
        REFIID in_clsid,
        int in_size,
        const unsigned char *in_data);

    HRESULT (STDMETHODCALLTYPE *Unregister)(
        ISCMClsFactoryResloveService* This,
        REFIID in_clsid);

    HRESULT (STDMETHODCALLTYPE *Query)(
        ISCMClsFactoryResloveService* This,
        REFIID in_clsid,
        int in_size,
        unsigned char *out_data,
        int *out_length);

    END_INTERFACE
} ISCMClsFactoryResloveServiceVtbl;
interface ISCMClsFactoryResloveService {
    CONST_VTBL ISCMClsFactoryResloveServiceVtbl* lpVtbl;
};

#ifdef COBJMACROS
/*** IUnknown methods ***/
#define ISCMClsFactoryResloveService_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ISCMClsFactoryResloveService_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ISCMClsFactoryResloveService_Release(This) (This)->lpVtbl->Release(This)
/*** ISCMClsFactoryResloveService methods ***/
#define ISCMClsFactoryResloveService_Register(This,in_clsid,in_size,in_data) (This)->lpVtbl->Register(This,in_clsid,in_size,in_data)
#define ISCMClsFactoryResloveService_Unregister(This,in_clsid) (This)->lpVtbl->Unregister(This,in_clsid)
#define ISCMClsFactoryResloveService_Query(This,in_clsid,in_size,out_data,out_length) (This)->lpVtbl->Query(This,in_clsid,in_size,out_data,out_length)
#endif

#endif

HRESULT STDMETHODCALLTYPE ISCMClsFactoryResloveService_Register_Proxy(
    ISCMClsFactoryResloveService* This,
    REFIID in_clsid,
    int in_size,
    const unsigned char *in_data);
void __RPC_STUB ISCMClsFactoryResloveService_Register_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);
HRESULT STDMETHODCALLTYPE ISCMClsFactoryResloveService_Unregister_Proxy(
    ISCMClsFactoryResloveService* This,
    REFIID in_clsid);
void __RPC_STUB ISCMClsFactoryResloveService_Unregister_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);
HRESULT STDMETHODCALLTYPE ISCMClsFactoryResloveService_Query_Proxy(
    ISCMClsFactoryResloveService* This,
    REFIID in_clsid,
    int in_size,
    unsigned char *out_data,
    int *out_length);
void __RPC_STUB ISCMClsFactoryResloveService_Query_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);

#endif  /* __ISCMClsFactoryResloveService_INTERFACE_DEFINED__ */

#ifndef __ISCMApartMentResloveService_FWD_DEFINED__
#define __ISCMApartMentResloveService_FWD_DEFINED__
typedef interface ISCMApartMentResloveService ISCMApartMentResloveService;
#endif

/*****************************************************************************
 * ISCMApartMentResloveService interface
 */
#ifndef __ISCMApartMentResloveService_INTERFACE_DEFINED__
#define __ISCMApartMentResloveService_INTERFACE_DEFINED__

DEFINE_GUID(IID_ISCMApartMentResloveService, 0x03ee1f1c, 0x7f8b, 0x4fdb, 0x86,0x0a, 0x02,0x95,0x85,0x6c,0xdb,0x21);
#if defined(__cplusplus) && !defined(CINTERFACE)
interface ISCMApartMentResloveService : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Register(
        OXID in_oxid,
        const char *in_binding) = 0;

    virtual HRESULT STDMETHODCALLTYPE Unregister(
        OXID in_oxid) = 0;

    virtual HRESULT STDMETHODCALLTYPE Query(
        OXID in_oxid,
        int in_binding_size,
        char *out_binding) = 0;

};
#else
typedef struct ISCMApartMentResloveServiceVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ISCMApartMentResloveService* This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ISCMApartMentResloveService* This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ISCMApartMentResloveService* This);

    /*** ISCMApartMentResloveService methods ***/
    HRESULT (STDMETHODCALLTYPE *Register)(
        ISCMApartMentResloveService* This,
        OXID in_oxid,
        const char *in_binding);

    HRESULT (STDMETHODCALLTYPE *Unregister)(
        ISCMApartMentResloveService* This,
        OXID in_oxid);

    HRESULT (STDMETHODCALLTYPE *Query)(
        ISCMApartMentResloveService* This,
        OXID in_oxid,
        int in_binding_size,
        char *out_binding);

    END_INTERFACE
} ISCMApartMentResloveServiceVtbl;
interface ISCMApartMentResloveService {
    CONST_VTBL ISCMApartMentResloveServiceVtbl* lpVtbl;
};

#ifdef COBJMACROS
/*** IUnknown methods ***/
#define ISCMApartMentResloveService_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ISCMApartMentResloveService_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ISCMApartMentResloveService_Release(This) (This)->lpVtbl->Release(This)
/*** ISCMApartMentResloveService methods ***/
#define ISCMApartMentResloveService_Register(This,in_oxid,in_binding) (This)->lpVtbl->Register(This,in_oxid,in_binding)
#define ISCMApartMentResloveService_Unregister(This,in_oxid) (This)->lpVtbl->Unregister(This,in_oxid)
#define ISCMApartMentResloveService_Query(This,in_oxid,in_binding_size,out_binding) (This)->lpVtbl->Query(This,in_oxid,in_binding_size,out_binding)
#endif

#endif

HRESULT STDMETHODCALLTYPE ISCMApartMentResloveService_Register_Proxy(
    ISCMApartMentResloveService* This,
    OXID in_oxid,
    const char *in_binding);
void __RPC_STUB ISCMApartMentResloveService_Register_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);
HRESULT STDMETHODCALLTYPE ISCMApartMentResloveService_Unregister_Proxy(
    ISCMApartMentResloveService* This,
    OXID in_oxid);
void __RPC_STUB ISCMApartMentResloveService_Unregister_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);
HRESULT STDMETHODCALLTYPE ISCMApartMentResloveService_Query_Proxy(
    ISCMApartMentResloveService* This,
    OXID in_oxid,
    int in_binding_size,
    char *out_binding);
void __RPC_STUB ISCMApartMentResloveService_Query_Stub(
    IRpcStubBuffer* This,
    IRpcChannelBuffer* pRpcChannelBuffer,
    PRPC_MESSAGE pRpcMessage,
    DWORD* pdwStubPhase);

#endif  /* __ISCMApartMentResloveService_INTERFACE_DEFINED__ */

/*****************************************************************************
 * SCMClsFactoryResloveService coclass
 */

DEFINE_GUID(CLSID_SCMClsFactoryResloveService, 0x15582959, 0x3bbf, 0x4926, 0x82,0x48, 0x85,0xf4,0xb0,0x66,0x29,0xc1);

#ifndef __SCMClsFactoryResloveService_FWD_DEFINED__
#define __SCMClsFactoryResloveService_FWD_DEFINED__
typedef struct SCMClsFactoryResloveService SCMClsFactoryResloveService;
#endif /* defined __SCMClsFactoryResloveService_FWD_DEFINED__ */

/*****************************************************************************
 * SCMApartMentResloveService coclass
 */

DEFINE_GUID(CLSID_SCMApartMentResloveService, 0x1558295a, 0x3bbf, 0x4926, 0x82,0x48, 0x85,0xf4,0xb0,0x66,0x29,0xc1);

#ifndef __SCMApartMentResloveService_FWD_DEFINED__
#define __SCMApartMentResloveService_FWD_DEFINED__
typedef struct SCMApartMentResloveService SCMApartMentResloveService;
#endif /* defined __SCMApartMentResloveService_FWD_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __WIDL_SCM_API_H */
