/*** Autogenerated by WIDL 1.1.6 from irot.idl - Do not edit ***/
#include "rpc.h"
#include "rpcndr.h"

#ifndef __WIDL_IROT_H
#define __WIDL_IROT_H
#ifdef __cplusplus
extern "C" {
#endif

#include "wtypes.h"
#define IROT_PROTSEQ {'n','c','a','l','r','p','c',0}
#define IROT_ENDPOINT {'i','r','o','t',0}
typedef struct tagMonikerComparisonData {
    ULONG ulCntData;
    BYTE abData[1];
} MonikerComparisonData;
typedef struct tagInterfaceData {
    ULONG ulCntData;
    BYTE abData[1];
} InterfaceData;
typedef InterfaceData *PInterfaceData;
typedef struct tagInterfaceList {
    ULONG size;
    PInterfaceData interfaces[1];
} InterfaceList;
typedef InterfaceList *PInterfaceList;
typedef DWORD IrotCookie;
typedef handle_t IrotHandle;
typedef void *IrotContextHandle;
void * __RPC_USER MIDL_user_allocate(size_t);
void __RPC_USER MIDL_user_free(void *);

/*****************************************************************************
 * Irot interface (v0.2)
 */
#ifndef __Irot_INTERFACE_DEFINED__
#define __Irot_INTERFACE_DEFINED__

extern RPC_IF_HANDLE Irot_v0_2_c_ifspec;
extern RPC_IF_HANDLE Irot_v0_2_s_ifspec;
HRESULT IrotRegister(
    IrotHandle h,
    const MonikerComparisonData *moniker_data,
    const InterfaceData *object,
    const InterfaceData *moniker,
    const FILETIME *time,
    DWORD grfFlags,
    IrotCookie *cookie,
    IrotContextHandle *ctxt_handle);

HRESULT IrotRevoke(
    IrotHandle h,
    IrotCookie cookie,
    IrotContextHandle *ctxt_handle,
    PInterfaceData *object,
    PInterfaceData *moniker);

HRESULT IrotIsRunning(
    IrotHandle h,
    const MonikerComparisonData *moniker_data);

HRESULT IrotGetObject(
    IrotHandle h,
    const MonikerComparisonData *moniker_data,
    PInterfaceData *obj,
    IrotCookie *cookie);

HRESULT IrotNoteChangeTime(
    IrotHandle h,
    IrotCookie cookie,
    const FILETIME *time);

HRESULT IrotGetTimeOfLastChange(
    IrotHandle h,
    const MonikerComparisonData *moniker_data,
    FILETIME *time);

HRESULT IrotEnumRunning(
    IrotHandle h,
    PInterfaceList *list);


#endif  /* __Irot_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

void __RPC_USER IrotContextHandle_rundown(IrotContextHandle);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __WIDL_IROT_H */
