
/*** Autogenerated by WIDL 1.1.6 - Do not edit ***/

#include <objbase.h>
#include <rpcproxy.h>

#ifdef __cplusplus
extern "C" {
#endif

EXTERN_PROXY_FILE(talk)

PROXYFILE_LIST_START
/* Start of list */
  REFERENCE_PROXY_FILE(talk),
/* End of list */
PROXYFILE_LIST_END

DLLDATA_ROUTINES(aProxyFileList, GET_DLL_CLSID)

#ifdef __cplusplus
}
#endif

