/*** Autogenerated by WIDL 1.1.6 from dxgi.idl - Do not edit ***/
#include <rpc.h>
#include <rpcndr.h>

#ifndef __WIDL_DXGI_H
#define __WIDL_DXGI_H
#ifdef __cplusplus
extern "C" {
#endif

#include <dxgitype.h>
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __WIDL_DXGI_H */
